### ISSUE TITLE
BundleID not found on object of type SKTAppInfo

### ISSUE THREAD

**Issue by jimmybaker** [callstack/react-native-socket-mobile#7]
It looks like SKTAppInfo renamed `BundleID` to `AppID`. I just tried building and got this error: 
<img width="1195" alt="image 2018-08-28 at 12 18 57 pm" src="https://user-images.githubusercontent.com/50668/44739303-04bf8000-aabd-11e8-8e0e-b06f6f4c66d2.png">

Updating it to `AppID` instead of `BundleID` fixes the issue. I'm using SKTCaptureObjC (1.0.151)

I'll send over a PR shortly.

**Comment by ferrannp** [comment]
Thank you!
